name: openstack-full-installer-installer
target_software:
  - openstack
executable: "start.py"
config:


parameter:
  hostname:
  account:
    id:
    pw:
  nic:
    -
      macaddr:
      ipaddr:
      subnet:
  image:
    dist: ubuntu
    version: 16.04