# coding: utf-8

"""
    SmartX Cluster Post - RESTful APIs

    An API server for DsP Post.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: jsshin@smartx.kr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.dsp_api import DspApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDspApi(unittest.TestCase):
    """DspApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.dsp_api.DspApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_dspcompose(self):
        """Test case for dspcompose

        Trigger boxes composition  # noqa: E501
        """
        pass

    def test_dsprelease(self):
        """Test case for dsprelease

        Trigger boxes release  # noqa: E501
        """
        pass

    def test_get_ds_p_installer_by_name(self):
        """Test case for get_ds_p_installer_by_name

        Get all installers supported by the DsP on the post  # noqa: E501
        """
        pass

    def test_get_ds_p_installer_list(self):
        """Test case for get_ds_p_installer_list

        Get all installers supported by the DsP on the post  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
