# coding: utf-8

"""
    SmartX Cluster Post - RESTful APIs

    An API server for DsP Post.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: jsshin@smartx.kr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.installer import Installer  # noqa: E501
from swagger_client.rest import ApiException


class TestInstaller(unittest.TestCase):
    """Installer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstaller(self):
        """Test Installer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.installer.Installer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
