# coding: utf-8

# flake8: noqa
"""
    SmartX Cluster Post - RESTful APIs

    An API server for DsP Post.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: jsshin@smartx.kr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.installer import Installer
